### ISSUE TITLE
[bug] Frames don't disappear

### ISSUE THREAD

**Issue by Romz24** [PTOM76/EnhancedQuarries#10]
If we set up a quarry, power it up and break it in the process of creating frames, the frames will not disappear and we will have to break them manually.

![image](https://user-images.githubusercontent.com/2458113/134826606-f0a87d3d-2d97-40a5-a795-b39b58786aa5.png)

**Comment by PTOM76** [comment]
This is unavoidable due to the specifications.
As for the destruction of the frame, the one that touches Quarry is chain-destroyed.

Do you need an item to destroy the frame?

**Comment by Romz24** [comment]
You should not add a new item to destroy the frames, it will be superfluous.
