### ISSUE TITLE
Crash with Quarries (1.17.1)

### ISSUE THREAD

**Issue by DatrixTHLK** [PTOM76/EnhancedQuarries#16]
Minecraft: 1.17.1
Fabric: 0.11.6
Enhanced Quarries: 2.4.0_RCS
Crashlog: https://gist.github.com/DatrixTHLK/a92808a2275a4109ddc02237f2a898b6

Hi there,

Some reason Not Enough Crashes and Blame are picking out this mod to be having problems with my modlist. Without it it works fine and with it it will crash. Is there anything I'm missing in regards to API, Lib or Coremod?

**Comment by PTOM76** [comment]
Probably this mod doesn't seem to be causing an error and Iris seems to be causing an error.
https://github.com/IrisShaders/Iris/issues/492

Looking at the package, I think it's a bug by Iris

**Comment by DatrixTHLK** [comment]
Oh, ok. Thanks for the response.  I appreciate it.
