### ISSUE TITLE
Minecraft 1.19 requirde techreborn stuff

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [PTOM76/EnhancedQuarries#24]
Version 
fabric-loader-0.13.3-22w12a

hello,

please provide a link to the required TECHREBORN stuff.

As a programmer you should test your stuff bfore publishing.
Therefore you hav a TechReborn version for 1.19

Same for Advanced Reborn

Please provide
mfg

**Comment by PTOM76** [comment]
thank you for reporting!
for 1.19 snapshots, the 1.18.2 mods are likely to work, but for TRs it doesn't seem to be the case.
i'm sorry.
i've deleted the 1.19 snapshot's tag because it's confusing.
