### ISSUE TITLE
1.21 - Server/Game Crashing when Opening UI or Enhanced Quarry upgraded with Luck Module.

### ISSUE THREAD

**Issue by georgeule-cloud** [PTOM76/EnhancedQuarries#27]
So as the title says the game or server will crash on those scenarios, haven't found anything else yet.
Attaching the Crash log of the server:
[crash-2024-07-11_04.32.23-server.txt](https://github.com/user-attachments/files/16171513/crash-2024-07-11_04.32.23-server.txt)

**Comment by georgeule-cloud** [comment]
I will test it without the other mods, I'll update here.

**Comment by georgeule-cloud** [comment]
Just confirmed that the Luck module is crashing the Game on Fabric latest version. Without any other mod than JEI.

**Comment by georgeule-cloud** [comment]
@PTOM76

**Comment by xardius** [comment]
Same problem here. After inserting the Luck Module the game crashes when the Quarry starts to "dig". The build up process where the frame is gets constructed and the blocks in the frame are removed works just fine. But when the Quarry starts to dig the very first block it crashes the game.

Mod version 1.4.8 / Minecraft 1.21 / Fabric.
I don't use Tech Reborn.

**Comment by xardius** [comment]
Silk Touch Module also Crashes the game :(

**Comment by PTOM76** [comment]
Did you already solve it with MCPitanLib 2.3.8?
